### ISSUE TITLE
Consider using stream-observer in tests

### ISSUE THREAD

**Issue by vweevers** [Level/iterator-stream#35]
Atm the tests (specifically, the ones that test event order) attach a `data` listener:

https://github.com/Level/iterator-stream/blob/9460d1b29e5867f28804b741b7c504d1a9091618/test.js#L306-L307

Which has a side effect. But with [`stream-observer`](https://github.com/watson/stream-observer) we can monitor `data` events without going into flowing mode. Then, for tests that need it, we can do an explicit `stream.resume()`. At least for:

https://github.com/Level/iterator-stream/blob/9460d1b29e5867f28804b741b7c504d1a9091618/test.js#L43

https://github.com/Level/iterator-stream/blob/9460d1b29e5867f28804b741b7c504d1a9091618/test.js#L67

**Comment by ralphtheninja** [comment]
I was thinking the same the other day. At least that it would be useful for testing purposes in general.
