### ISSUE TITLE
Add tests with end-of-stream (or stream.finished from node 10)

### ISSUE THREAD

**Issue by vweevers** [Level/iterator-stream#38]
Because atm I'm not sure if #34 is a minor or major. Streams are easy to break.

We can test a few scenarios with `end-of-stream`, assert that they don't result in a `premature close` error.

Also, because `end-of-stream` will call back on an `error` event (before the `close` event), we should test that the iterator was already ended at that time. It should be safe to do:

```js
var eof = require('end-of-stream')

eof(db.createReadStream(), function (err) {
  db.close(..)
})
```

**Comment by vweevers** [comment]
Though some of these things are covered by current tests, it can't hurt to additionally check correctness with `end-of-stream`, which is battle-tested and idiomatic (enough that it landed in core).

**Comment by ralphtheninja** [comment]
> enough that it landed in core

I had no idea about this. Very nice!

**Comment by ralphtheninja** [comment]
Oh wait, how exactly did it land in core? At first I thought you could require it directly in node.

**Comment by vweevers** [comment]
https://nodejs.org/api/stream.html#stream_stream_finished_stream_callback

**Comment by vweevers** [comment]
Hmm but: it will also call back on `end`, which fires in a tick before `close` (and before the iterator has ended). I'm hoping this was discussed in node (with a resulting recommended best practice). I've got some reading to do :)

**Comment by ralphtheninja** [comment]
Spoken like a true researcher! :smile:

**Comment by vweevers** [comment]
Streams are still weird. Given a readable stream, `end-of-stream` will call back:

- on `end` (possibly followed by a `close` event, which is optional)
- on `error` (possibly followed by a `close` event, which is optional unless the stream was destroyed)
- on `close` (which means the stream was destroyed prematurely)

And in node 10, `fs.createReadStream` doesn't emit `close` after `error` if you do `rs.destroy(err)`, but `require('stream').Readable` does.
