### ISSUE TITLE
Release 4.0.0

### ISSUE THREAD

**Issue by ralphtheninja** [Level/iterator-stream#43]
See https://github.com/Level/iterator-stream/pull/42#issuecomment-417014332

**Comment by vweevers** [comment]
@ralphtheninja Though we don't have an official browser support matrix for `level-iterator-stream`, I do think a major bump is in order (on both `level-iterator-stream` and `levelup`), given that we [do support IE10](https://github.com/Level/levelup/blob/c0858a1360dd0be763f56aad8571b3ea801fb8b1/.airtap.yml#L7) in the current version of `levelup`.
