### ISSUE TITLE
NPM update

### ISSUE THREAD

**Issue by egirshov** [Level/iterator-stream#9]
There are some updates since 1.3.1, care to publish a new version to npm?

**Comment by ralphtheninja** [comment]
There are no real updates since 1.3.1, just devDependencies and ci related things

**Comment by egirshov** [comment]
It's been a while since I opened this PR, but IIRC the reason for me was changed 'readable-stream' version which is in the regular dependencies (not dev).

**Comment by ralphtheninja** [comment]
@egirshov Aaah ok. Latest `readable-stream` version seems to be `2.3.3` and should be taken care of by `"readable-stream": "^2.0.5"`
